---
abstract: 'Lightweight and efficient NCBI taxonomic manager'
author:
  - 'Miguel Pignatelli <emepyc@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-LITE-Taxonomy-NCBI
no_index:
  directory:
    - t
    - inc
requires:
  Bio::LITE::Taxonomy: 0.07
  Test::More: 0.87
version: 0.09
